### PR TITLE
Upgrade waypoints to version 4.0.1

### PR DESCRIPTION
**Pull request by meowsus**
Pulling from the [latest](https://github.com/imakewebthings/waypoints/tree/latest) tag on the parent repo.

### CODE REVIEW

**Comment by meowsus** [comment]
I'd be much obliged if'n y'd merge and push that gem :)

**Comment by meowsus** [comment]
Friendly bump!

**Comment by meowsus** [comment]
@chardos I'd be more than happy to take over this repository if you don't have the time to maintain it. Just let me know.

**Comment by meowsus** [comment]
:D

**Comment by chardos** [comment]
Sorry took so long man!

**Comment by meowsus** [comment]
No problem! You're an incredible human!

**Comment by meowsus** [comment]
If you wouldn't mind also releasing to rubygems.org when you get a chance.

https://rubygems.org/gems/waypoints_rails is still at v3.0.0

Thanks so much!

**Comment by chardos** [comment]
Sorry for the terrible response time, but the gem is now pushed!

**Comment by meowsus** [comment]
Thanks again, man!

**Pull request merged**
